language: php
commands:
  create:
  - kool docker kooldev/php:7.4 composer create-project --prefer-dist laravel/laravel
questions:
  database:
    message: What database service do you want to use
    options:
      mysql8: MySQL 8.0
      mysql57: MySQL 5.7
      postgresql13: PostgreSQL 13.0
      none: none
  cache:
    message: What cache service do you want to use
    options:
      redis6: Redis 6.0
      memcached16: Memcached 1.6
      none: none

